server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://34.95.237.57:3306/xmendb
    username: root
    password: NIMeJu0bgA7pu67h
  cloud:
    gcp:
      sql:
        instance-connection-name: xmenproject:southamerica-east1:xmen-database
        database-name: xmendb
  jpa:
    hibernate:
      use-new-id-generator-mappings: false